import * as fs from "fs/promises";
import * as path from "path";

export interface LoomConfig {
  /** Root directory for .loom knowledge base */
  loomDir: string;
  /** Whether to auto-commit changes to Git */
  autoCommit: boolean;
  /** Whether to auto-push to remote after commit */
  autoPush: boolean;
  /** Default branch name for Loom operations */
  branch: string;
  /** Git commit message prefix */
  commitPrefix: string;
}

const DEFAULT_CONFIG: LoomConfig = {
  loomDir: ".loom",
  autoCommit: true,
  autoPush: false,
  branch: "main",
  commitPrefix: "loom",
};

const CONFIG_FILE = ".loomrc.json";

export async function loadConfig(workDir: string): Promise<LoomConfig> {
  const configPath = path.join(workDir, CONFIG_FILE);
  try {
    const raw = await fs.readFile(configPath, "utf-8");
    const userConfig = JSON.parse(raw) as Partial<LoomConfig>;
    return { ...DEFAULT_CONFIG, ...userConfig };
  } catch {
    return { ...DEFAULT_CONFIG };
  }
}

export function resolveLoomPath(workDir: string, config: LoomConfig): string {
  return path.isAbsolute(config.loomDir)
    ? config.loomDir
    : path.join(workDir, config.loomDir);
}

const LOOM_SUBDIRS = ["concepts", "decisions", "threads"] as const;

export type LoomCategory = (typeof LOOM_SUBDIRS)[number];

export async function ensureLoomStructure(loomRoot: string): Promise<void> {
  await fs.mkdir(loomRoot, { recursive: true });
  for (const sub of LOOM_SUBDIRS) {
    await fs.mkdir(path.join(loomRoot, sub), { recursive: true });
  }
  await fs.mkdir(path.join(loomRoot, "schema"), { recursive: true });

  const indexPath = path.join(loomRoot, "index.md");
  try {
    await fs.access(indexPath);
  } catch {
    const now = new Date().toISOString();
    await fs.writeFile(
      indexPath,
      `---
created: ${now}
updated: ${now}
---

# Loom System Index

> Auto-generated by Loom. This file maps all knowledge woven from AI conversations.

## Concepts

_No concepts yet._

## Decisions

_No decisions yet._

## Threads

_No threads yet._
`,
    );
  }

  const technicalSchemaPath = path.join(loomRoot, "schema", "technical.md");
  try {
    await fs.access(technicalSchemaPath);
  } catch {
    await fs.writeFile(
      technicalSchemaPath,
      `# Technical Graph Skeleton

> Macro technical memory backbone. Keep it stable and update incrementally.

## Entities

- Module
- Service
- API
- DataStore
- TechDecision

## Relations

- depends_on
- implements
- owns_data
- affects
- supersedes

## Current System Map

- Loom MCP Server -> depends_on -> Weaver Logic
- Weaver Logic -> depends_on -> Git Sync
- Loom MCP Server -> exposes -> loom_weave / loom_trace / loom_index / loom_probe_start / loom_probe_commit

## Update Rule

- When adding a new core capability, append one node and at least one edge.
`,
    );
  }

  const businessSchemaPath = path.join(loomRoot, "schema", "business.md");
  try {
    await fs.access(businessSchemaPath);
  } catch {
    await fs.writeFile(
      businessSchemaPath,
      `# Business Graph Skeleton

> Macro business memory backbone for goals, domains, and constraints.

## Domains

- Product Experience
- Engineering Efficiency
- Team Collaboration

## Core Objects

- User Request
- Decision
- Capability
- Constraint
- Outcome

## Relations

- drives
- constrains
- enables
- impacts

## Current Objective Map

- User Request -> drives -> Capability: proactive inquiry memory
- Capability -> enables -> Engineering Efficiency
- Constraint: no extra model key -> constrains -> Solution Architecture

## Update Rule

- For each major feature, add "why this matters" edge in this map.
`,
    );
  }
}
